name: challenge

on: push

jobs:
    job1:
        name: First Job
        runs-on: ubuntu-latest
        steps:
            - name: Step one
            - name: Step two
    job2:
        name: Second Job
        runs-on: windows-latest
        steps:
            - name: Step one
            - name: Step two
    job3:
        name: Third Job
        runs-on: macos-latest
        steps:
            - name: Step one
            - name: Step two
    job4:
        needs: [job1,job2,job3]
        name: Fourth Job
        runs-on: mac0s-latest
        steps:
            - name: Step one
            - name: Step two        
    
